version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/to-do
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        container_name: todo_nginx
        depends_on:
            - app
            - npm

    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www/to-do
        container_name: todo_app
        depends_on:
            - db

    db:
        image: mysql:8.4
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: to-do
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8081:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: todo_db

    npm:
        image: node:18
        working_dir: /var/www/to-do
        command: ["npm", "run", "dev", "--", "--host"]
        # command: ["npm", "run", "build"]
        ports:
            - 5173:5173
        volumes:
            - ./:/var/www/to-do
        container_name: todo_npm
